mongodb:
  image: mongo
  container_name: mongo-bitcore
  ports:
    - "3503:27017"
  volumes:
    - ../data:/data/db
  command: mongod --smallfiles --logpath=/dev/null # -- quiet
  restart: always

bitcore-node:
  build: .
  dockerfile: Dockerfile
  container_name: bitcore
  links:
    - mongodb
  ports:
    - "3000:3000"
    - "8200:8200"
  restart: always